### ISSUE TITLE
ImportError  'dtreeviz' while import from explainerdashboard

### ISSUE THREAD

**Issue by hadoop-cloud** [oegedijk/explainerdashboard#255]
Hi Community,

I am learning explainability techniques, i found this very promising open source package.
I am facing an issue while i does an import  .

Any help here would be really great

from explainerdashboard import ClassifierExplainer, RegressionExplainer

`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-624a3479cf06> in <module>()
      1 from sklearn.ensemble import RandomForestClassifier
      2 # from explainerdashboard.datasets import titanic_survive
----> 3 from explainerdashboard import ClassifierExplainer, RegressionExplainer

/home/user/.local/lib/python3.6/site-packages/explainerdashboard/__init__.py in <module>()
      2 ___version__ = "0.3.8.2"
      3 
----> 4 from .explainers import ClassifierExplainer, RegressionExplainer
      5 from .dashboards import ExplainerDashboard, ExplainerHub, InlineExplainer

/home/user/.local/lib/python3.6/site-packages/explainerdashboard/explainers.py in <module>()
     25 import shap
     26 
---> 27 from dtreeviz.trees import ShadowDecTree, dtreeviz
     28 
     29 from sklearn.model_selection import KFold

ImportError: cannot import name 'dtreeviz'`

**Comment by hadoop-cloud** [comment]
i think there is no dtreeviz module inside dtreeviz

 ifails here
 from dtreeviz.trees import ShadowDecTree, dtreeviz

**Comment by MinaKanak** [comment]
I'm having the same issue with cloudera platform

**Comment by AkshayRShiraguppi** [comment]
This usually has to do with dependent libraries. I'd try upgrading or downgrading shap to fix it.

**Comment by oegedijk** [comment]
Hi, this should be fixed in the latest released version (0.4.2) could you confirm?

**Comment by hadoop-cloud** [comment]
Yes, it seems that it worked on Colab notebook.
but my jupyter instance still shows the same error. Not sure may be due to env issues.
Thanks for your reply.
